variables:
  VERSION: jq -r .version package.json
  BIN_NAME: ${CI_PROJECT_NAME}
  ARTIFACTS_DIR: artifacts
  GO_PROJECT: gitlab.com/${CI_PROJECT_PATH}
  GITLAB_ACCESS_TOKEN: ${GITLAB_TOKEN}

stages:
  - mr_test
  - build
  - tag
  - release

check_version:
  stage: mr_test
  script:
    - if [ $(git diff --name-only HEAD^ -- package.json | wc -l) -ne 1 ]; then echo "detected new release"; else echo "package.json hasn't changed'"; exit 1; fi
  only:
    - merge_requests

go_test:
  stage: mr_test
  image: golang:1.14
  before_script:
    - mkdir -p ${GOPATH}/src/${GO_PROJECT}
    - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}/`eval $VERSION`/
    - go get -u github.com/jcmturner/gokrb5/v8/client github.com/jcmturner/gokrb5/v8/config github.com/jcmturner/gokrb5/v8/credentials github.com/jcmturner/gokrb5/v8/spnego
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
    - cd ${GOPATH}/src/${GO_PROJECT}
  script:
    - go test -v -cover gorkscrew.go
  only:
    - merge_requests


build:
  stage: build
  image: golang:1.14
  before_script:
    - mkdir -p ${GOPATH}/src/${GO_PROJECT}
    - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}/`eval $VERSION`/
    - go get -u github.com/jcmturner/gokrb5/v8/client github.com/jcmturner/gokrb5/v8/config github.com/jcmturner/gokrb5/v8/credentials github.com/jcmturner/gokrb5/v8/spnego
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
    - cd ${GOPATH}/src/${GO_PROJECT}
  script:
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME} gorkscrew.go
  artifacts:
    expire_in: '1 hour'
    paths:
      - ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  only:
    - master


tag:
  stage: tag
  image: alpine:latest
  script:
    - apk --update add git jq
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git config push.default simple
    - git remote set-url origin https://${GITLAB_USER_LOGIN}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - if ! $(git remote show github 2&>1 /dev/null); then git remote add github https://${GITLAB_USER_LOGIN}:${GITHUB_TOKEN}@github.com/${GITLAB_USER_LOGIN}/gorkscrew.git; fi
    - git remote -v
    - git checkout master
    - git tag -a `eval $VERSION` -m "`eval $VERSION`"
    - git push --tags
    - git push github HEAD:master
  only:
    - master


release:
  stage: release
  image: inetprocess/gitlab-release
  script:
    - gitlab-release --message 'Release `eval $VERSION`' ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  only:
    - master
