name: go_build

on:
  release:
    types: [created]

jobs:
  build:
    name: build_to_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Read release.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version

    - name: Build gorkscrew binary
      uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.14.7.linux-amd64.tar.gz"
        pre_command: go get -v github.com/jcmturner/gokrb5/v8/client github.com/jcmturner/gokrb5/v8/config github.com/jcmturner/gokrb5/v8/credentials github.com/jcmturner/gokrb5/v8/spnego
