name: pr_test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test gorkscew PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3

      - name: check if package.json has been modified
        run: |
          grep package.json $HOME/files.json

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Get dependencies
        run: |
          go get -v github.com/jcmturner/gokrb5/v8/config github.com/jcmturner/gokrb5/v8/client github.com/jcmturner/gokrb5/v8/credentials github.com/jcmturner/gokrb5/v8/spnego

      - name: Run go test
        run: go test -v gorkscrew.go
